### ISSUE TITLE
undefined index SERVER_PROTOCOL when using ES in cron job. 

### ISSUE THREAD

**Issue by gokigoks** [basemkhirat/elasticsearch#105]
This happens only when using paginate. Whats the work around for this?

**Comment by basemkhirat** [comment]
Fixed Now. Please update.

LengthAwarePaginator requires HTTP request params like $_SERVER which is undefined in PHP console environment.

if we are working on a scripting code, the best practice is to use scan and scroll queries. It's too faster than paginate.
