### ISSUE TITLE
str_contains()

### ISSUE THREAD

**Issue by shota-mentesh** [basemkhirat/elasticsearch#109]
As of Laravel 5.8 str_contains() was deprecated, in 6.0 it was removed.

The issue lies in ElasticsearchServiceProvider.php:49

```
if (str_contains($this->app->version(), 'Lumen')) {
    $this->app->configure("es");
}
```

`str_contains()` needs to be changed to `\Str::contains()`.

**Comment by basemkhirat** [comment]
Fixed in V1.4. Update now.
