### ISSUE TITLE
how to use orwhere in basemkhirat/elasticsearch package

### ISSUE THREAD

**Issue by maralbe** [basemkhirat/elasticsearch#11]
hi thanks for your great package.
i have a collection and wanna to do multiple searches...
so i wrote where clauses on it.. but it works like and where that i don't want that response..
i want do orwhere on my collection.
can you give me a solution how to write that?   

thanks

**Comment by basemkhirat** [comment]
hello @maralbe,

I'm sorry there is no way to run AND OR logic queries in current time. but now I am rebuilding some of my code to add compound AND OR logic queries keep in watching to be notified.

But you can use the raw() method to do that with native queries.

```php
ES::raw()->search([
    "index" => "my_index",
    "type" => "my_type",
    "body" => [
        "query" => [
            "bool" => [
                "should" => [[
                    "bool" => [
                        "must" => [[
                            "match" => [
                                "preference_1" => "Apples"
                            ]
                        ], [
                            "match" => [
                                "preference_2" => "Bananas"
                            ]
                        ]]
                    ]
                ], [
                    "bool" => [
                        "must" => [[
                            "match" => [
                                "preference_1" => "Apples"
                            ]
                        ], [
                            "match" => [
                                "preference_2" => "Cherries"
                            ]
                        ]]
                    ]
                ], [
                    "match" => [
                        "preference_1" => "Grapefruit"
                    ]
                ]]
            ]
        ]
    ]
]);

```

This query will match `(preference_1 = Apples AND preference_2 = Bananas) OR (preference_1 = Apples AND preference_2 = Cherries) OR preference_1 = Grapefruits`.
is it helpful for you ?

**Comment by maralbe** [comment]
yes thanks..

but when i use raw.. the response is an array.. not a collection, so then i can not use methods on it, or do a chain query in that... 
so i think i should use raw in all of my search queries..

**Comment by basemkhirat** [comment]
Hi @maralbe,

if you want to use array queries and get a collection object, only update you package to version `0.9.5` and follow [docs](https://github.com/basemkhirat/elasticsearch#search-using-array-queries).

```php
ES::type("my_type")->body([
   "query" => [
            "bool" => [
                "should" => [[
                    "bool" => [
                        "must" => [[
                            "match" => [
                                "preference_1" => "Apples"
                            ]
                        ], [
                            "match" => [
                                "preference_2" => "Bananas"
                            ]
                        ]]
                    ]
                ], [
                    "bool" => [
                        "must" => [[
                            "match" => [
                                "preference_1" => "Apples"
                            ]
                        ], [
                            "match" => [
                                "preference_2" => "Cherries"
                            ]
                        ]]
                    ]
                ], [
                    "match" => [
                        "preference_1" => "Grapefruit"
                    ]
                ]]
            ]
        ]
])->get();

```

**Comment by AnFox** [comment]
Still no progress with this issue? It's very unhandy to generate raw query with complicated structure on the fly.

**Comment by nvanh020291** [comment]
Thanks for your great library
I want query data and How i can check multi column not empty ?
can you give me a solution how to write that?

thanks

**Comment by awais045** [comment]
> maralbe

found the solution or not ?? can you please tell me ??
