### ISSUE TITLE
Laravel elasticsearch 7.4  Conclusion with monolog 2.0.1

### ISSUE THREAD

**Issue by rinkujat25** [basemkhirat/elasticsearch#110]
i am installing basemkhirat/elasticsearch
and it conflicat with monolog 2.v
i am using laravel 6.x and elasticsearch 7.4 
any idea how to solve this issue
![Capture](https://user-images.githubusercontent.com/31273697/70410352-c4e39880-1a74-11ea-91ed-4a835e27b7d2.PNG)

**Comment by basemkhirat** [comment]
Fixed Now. Please update

**Comment by rinkujat25** [comment]
yes it's working 
thank you so much
