### ISSUE TITLE
This update just sent my production server down: 3acec81

### ISSUE THREAD

**Issue by osthafen** [basemkhirat/elasticsearch#115]
This update just sent my production server down:
https://github.com/basemkhirat/elasticsearch/commit/3acec8184716b67a404dbbde6e8c4707d3c35d5b

My ->body($search_body) included :
"_source" => [
                "includes" => [....], 
            ],

(it's with an s include**s**)

Which now was overwritten by:
protected $_source = [
        "include" => [],
        "exclude" => []
    ];

So everything was included and the memory could not handle it....

**Comment by basemkhirat** [comment]
Removed this version.

Clear the cached package on the server .
```
composer clear-cache
```
composer now will install version 1.4.4.
