### ISSUE TITLE
Data not filtered if the document containts "count" as field name

### ISSUE THREAD

**Issue by frozenex** [basemkhirat/elasticsearch#15]
Say if my document consists of the following fields,
[ "id" => 0, "tag" => "some-tag", "count" => 0]

When i perform the following filter... the results are not filtered accordingly...
ES::index(self::INDEX)->type($type)->where('count', '>', 0)->get();

If i change the count field to some other name say "total_count" it works....

Is "count" a reserved keyword in elastic search (or) is it a bug?

**Comment by basemkhirat** [comment]
No, `count` is not a reserved keyword. I tested it and works fine.

**Comment by basemkhirat** [comment]
Hi @frozenex,

No, `count` is not a reserved keyword. I tested it.

**Comment by basemkhirat** [comment]
Hi @frozenex,

This problem is fixed in version `0.9.8`. just upgrade you package.
