### ISSUE TITLE
pagination for huge number of records

### ISSUE THREAD

**Issue by ozza** [basemkhirat/elasticsearch#2]
hello,

first i want to thank you for your awesome work.

i'm trying to paginate one million+ records for to user. naturally i'm getting the "Result window is too large" error. is it possible to achieve this?

i read about the scroll function. but i don't know how to use the function with your library. can you help me about the subject?

thank you.

**Comment by basemkhirat** [comment]
you are welcome @ozza and sorry for being late.

I added support of building scan and scroll queries.

please update your package to version 0.6

you can see what you want here:
[https://github.com/basemkhirat/elasticsearch#scan-and-scroll-queries](https://github.com/basemkhirat/elasticsearch#scan-and-scroll-queries)

pleased to help you.

**Comment by ozza** [comment]
thank you very much @basemkhirat!

i'will try it tomorrow at work.

**Comment by ozza** [comment]
hello basem,

scroll function working very well. thank you again for that.

but i understand that scroll is not helping me with my current situation. what i need is a normal pagination (which you did already) with support of large sets of records (10k more default). is it achievable? 

btw i'm very new to elasticsearch, still trying to figure out how it works.

thanks.

**Comment by basemkhirat** [comment]
hello @ozza ,

I am using scroll queries for fast data reindexing as offset queries is not efficient for large data not to paginate records in a live website .

I think paginate() method is very efficient as elasticsearch return the available total records within response so we can calculate links by running one query not two queries such as relational databases like mysql [eloquent] and I think It will work well with large data amount, so don't be worry about the performance

did you mean [10K] => every records rendered in every single page or the total number ?

**Comment by ozza** [comment]
hello @basemkhirat 

if i try to paginate 10.001 results by 1000/per page, paginator gives me 11 pages which is true. and i can see all the data through page 1 to 10. but when i clicked to page 11 it gives me an error saying "Result window is too large".

i think elasticsearch is limited to fetch only 10.000 results by default. 

and i need to paginate nearly one million results. i don't know how is it possible but systems like kibana, elastic hq and some others capable of doing this. 

if you can suggest me anything it would be very appreciated.

thank you.

**Comment by basemkhirat** [comment]
hello @ozza,

I think that It's a server configuration related to `index.max_result_window` in `elasticsearch.yml` file.
Try to increase it and restart your service.
