### ISSUE TITLE
search exact value in hole type

### ISSUE THREAD

**Issue by maralbe** [basemkhirat/elasticsearch#23]
Hi basemkhirat

i want to search in my type.. 
and wrote all my queries, and work fine.. here i have a challenge!
i want to search in hole type... any field that exist, i wrote a query like this : 
    `

    "query" => [
          "bool" => [    
                 "must" => [
                         "query_string" => [
                                 "query" => $keyword_exact,
                                  "boost" => 1
                             ]
                      ]
               ]      
       ] 
`

it works, but i want to get documents with the exact query...
for example: if i search sales... i want this exact word, not 'resalat' or 'Assaluyeh' or... because of having letters 'sal' .

this was my issue, 
i hope it's clear for you
and thanks

**Comment by basemkhirat** [comment]
Hi @maralbe,

You can use this query to search with exact query string

```php
$documents = ES::type("your_type")->search('"'. $keyword .'"')->get();
```

Try it and tell me if this solution not work for you

**Comment by maralbe** [comment]
thanks for your response @basemkhirat.
i want to search using array queries..
in this case what to do?

**Comment by basemkhirat** [comment]
You are welcome @maralbe 
```php
$documents = ES::type("your_type")->body([
  "query" => [
      "bool" => [    
             "must" => [
                     "query_string" => [
                             "query" => '"'. $keyword .'"',
                              "boost" => 1
                         ]
                  ]
           ]      
   ] 
])->get();
```

**Comment by maralbe** [comment]
it didn't work

**Comment by intergalactisch** [comment]
Hi, 

Can I also use this to only search and show "Playstation" when also "Playstation 4", "Playstation 3" and "Playstation 2" are available?
`$keyword = 'Playstation';`
`$documents = ES::type("your_type")->search('"'. $keyword .'"')->get();`

**Comment by maralbe** [comment]
hi @intergalactisch 
in my case it didn't work... and my result are also includes  "Playstation 4", "Playstation 3" and "Playstation 2"

**Comment by basemkhirat** [comment]
Reading about elasticsearch keyword analyser may help you.
It's a native elasticsearch specific feature  but not included in the current builder package now but we are working on.
