### ISSUE TITLE
how to add mapping with scout driver

### ISSUE THREAD

**Issue by maralbe** [basemkhirat/elasticsearch#26]
hi 
in my case i am indexing with laravel scout.. 
and using this command
`php artisan scout:import "App\Post" `

question is, how can i add mapping during index?
i set configuration like all said in document, but it doesn't care about the configuration and just do the indexing...

is there any way to add mapping after index all my data? 
i prefer use curl.. but i don't know how to add mapping for an existing index

thanks

**Comment by basemkhirat** [comment]
There is no way. Update mapping after data indexing will not reflect without reindexing. It's elasticsearch specific senario.

I think you didn't update you mappings using `es:indices:update` or any other way using curl !

BUt if your application is not alive you can create a new index with new mappings and perform data indexing again.

The document you red should help you if you have index has data for production use without downtime.
