### ISSUE TITLE
Console commands missing (Lumen)

### ISSUE THREAD

**Issue by DonFlurry** [basemkhirat/elasticsearch#28]
I followed the manual inside a freshly created Lumen application up to the point where the first command is used

**$ php artisan es:indices:list**

It returns: 

>   [Symfony\Component\Console\Exception\CommandNotFoundException]  
>   There are no commands defined in the "es:indices" namespace.  

Listing all artisan commands shows that they are all missing. So my guess is that the application has a problem in the register function of the ElasticsearchServiceProvider.php where the commands are defined for command line use. 

I am using:
        "php": ">=7.1",
        "laravel/lumen-framework": "5.4.*",
        "basemkhirat/elasticsearch": "^1.0"

Any Idea what to do? Thankful for every helping hand!

**Comment by DonFlurry** [comment]
I found the source of the problem: 

I was right about the register function. You try to compare version numbers here but Lumen returns more than just the version number and therefore the result will always be false.

see: https://github.com/laravel/lumen-framework/issues/472

**Comment by basemkhirat** [comment]
Fixed. just upgrade you package to version `1.1`.
