### ISSUE TITLE
properties and _all

### ISSUE THREAD

**Issue by terion-name** [basemkhirat/elasticsearch#30]
Related to #20
Even now there is no possibility to control `_all` field, because type mapping is passed directly to `properties`. Because of this there is no possibility to tune `_all` field for a type (add analyzer, for example).

So config should be straight forward, like in elastic docs. This is a breaking change, however, so maybe should have some special key in config.. Or set it to 1.x release

**Comment by basemkhirat** [comment]
Thanks @terion-name you are right. It should have another release I just update the change log.
I will update the readme file for this warning message.
