### ISSUE TITLE
1.3 doesnot work with lumen/laravel 5.4 anymore

### ISSUE THREAD

**Issue by henningschumann** [basemkhirat/elasticsearch#46]
When we install version 1.3 via composer update our tests do not run anymore, if we downgrade to 1.2 everything works again.

Errors:

> phpunit
> PHP Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Notifications\Dispatcher] is not instantiable. in /[...]/vendor/illuminate/container/Container.php:895
Stack trace:
#0 /[...]/vendor/illuminate/container/Container.php(735): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /[...]/vendor/illuminate/container/Container.php(608): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /[...]/vendor/illuminate/container/Container.php(575): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 /[...]/vendor/laravel/lumen-framework/src/Application.php(210): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /[...]/vendor/laravel/lumen-framework/src/helpers.php(38): Laravel\Lumen\Application->make in /[...]/vendor/illuminate/container/Container.php on line 895`

**Comment by basemkhirat** [comment]
Hi @henningschumann 

Please try the version `1.3.1` and give me your feedback.

**Comment by henningschumann** [comment]
Yes it works with 1.3.1, thanks!
