### ISSUE TITLE
Raw queries, "match_all" error

### ISSUE THREAD

**Issue by ozza** [basemkhirat/elasticsearch#5]
hello,

i'm trying to execute:

```
$col = ES::raw()->search([
            "index" => "my_index",
            "type"  => "my_type",
            "body" => [
                "query" => [
                    "bool" => [
                        "must" => [
                            "match_all" => []
                        ]
                    ]
                ]
            ]
        ]);
```

and it throws an error:

`parsing_exception: [match_all] query malformed, no start_object after query name`

`match` is working fine. am i doing something wrong with the `match_all`?

by the way the raw query example on the main page still contains `:` signs. i think you forgot to change them with `=>`.

thank you.

**Comment by basemkhirat** [comment]
Hello @ozza,

This is an issue comes from the base [php elasticsearch package](https://github.com/elastic/elasticsearch-php/issues/495)  when `match_all` query has no parameters.

Try to update your code to 
``` 
   "match_all" => [
       "boost" => 1.0,
   ]
```

or passing an empty object

``` 
   "match_all" => (object)[]
```

Sorry for raw query example syntax. Fixed now

Thanks

**Comment by ozza** [comment]
thank you for the fast response!
