### ISSUE TITLE
Missing $_SERVER variables in tests

### ISSUE THREAD

**Issue by nospoon** [basemkhirat/elasticsearch#67]
When running functional tests, the $_SERVER variables are not present, which causes the library to throw errors and makes it untestable. Please use the $app->request->server instead of $_SERVER.

**Comment by masterjus** [comment]
Subscribe

**Comment by gokigoks** [comment]
#

**Comment by gokigoks** [comment]
#105 Is there any update for this please?

**Comment by on3n3o** [comment]
I've found quick workaround for this in my Lumen tests. I've added override to phpunit test
```
public function createApplication()
    {
        $app = parent::createApplication();
        $_SERVER['SERVER_PROTOCOL'] = 'http';
        $_SERVER['SERVER_PORT'] = 80;
        $_SERVER['SERVER_NAME'] = 'localhost';
        $_SERVER['REQUEST_URI'] = '';
        return $app;
    }
```
You can get this static variables from $app->request->server->...

**Comment by basemkhirat** [comment]
Fixed Now. Please update.

LengthAwarePaginator requires HTTP request params like $_SERVER which is undefined in PHP console environment.

if we are working on a scripting code, the best practice is to use scan and scroll queries. It's too faster than paginate.
