### ISSUE TITLE
Incompatible with laravel/scout ^5

### ISSUE THREAD

**Issue by jradtilbrook** [basemkhirat/elasticsearch#97]
This package does not work with laravel scout after version 4, where they changed the interface for the `Laravel\Scout\Engines\Engine` abstract class. I think the composer.json file should be updated to reflect this so it won't let you install it with incompatible peers.

You can see it was introduced in https://github.com/laravel/scout/commit/9f06b9c4d77879d53cf1680740b7f8bf19f78279

If you are willing, I would be able to provide a PR to add the `conflict` key to the composer to rectify this.

**Comment by ClaudioVarandas** [comment]
I have exactly the same issue:

Symfony\Component\Debug\Exception\FatalErrorException
Declaration of Basemkhirat\Elasticsearch\ScoutEngine::map($results, $model) must be compatible with Laravel\Scout\Engines\Engine::map(Laravel\Scout\Builder $builder, $results, $model)

**Comment by hernandezruizcesar** [comment]
Just now, i have the same probem, can anybody help us?

**Comment by jradtilbrook** [comment]
Seems like this might be unmaintained. I'm going to close this issue to clear out my own backlog
